### ISSUE TITLE
Recent tags didn't change

### ISSUE THREAD

**Issue by woefe** [Cisco-Talos/clamav-docker#38] opened 2024-01-14 14:11 UTC
Recent tags on the docker hub registry share the same image digest. Is that expected or is something not updating anymore? 

These tags share the same digest. Same is true for `_base` images.

- 1.2.1-21
- 1.2.1-22
- 1.2.1-23
- 1.2.1-24
- 1.2.1-25

https://hub.docker.com/r/clamav/clamav/tags?page=1&name=1.2.1-2

**Comment by micahsnyder** [comment] 2024-01-16 19:25
Thanks @woefe  will investigate.  I believe this is caused by caching in the build.

**Comment by micahsnyder** [comment] 2024-01-19 17:44
This should be fixed by https://github.com/Cisco-Talos/clamav-docker/pull/39

The next time we do the builds the images will be updated.

**Closed** 2024-01-19 17:44 UTC
